/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiSearchRouteImport } from './routes/api/search'
import { Route as ApiRequestAccessRouteImport } from './routes/api/request-access'
import { Route as ApiContainersRouteImport } from './routes/api/containers'
import { Route as ApiBrowseRouteImport } from './routes/api/browse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRequestAccessRoute = ApiRequestAccessRouteImport.update({
  id: '/api/request-access',
  path: '/api/request-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiContainersRoute = ApiContainersRouteImport.update({
  id: '/api/containers',
  path: '/api/containers',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBrowseRoute = ApiBrowseRouteImport.update({
  id: '/api/browse',
  path: '/api/browse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/request-access': typeof ApiRequestAccessRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/request-access': typeof ApiRequestAccessRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/browse': typeof ApiBrowseRoute
  '/api/containers': typeof ApiContainersRoute
  '/api/request-access': typeof ApiRequestAccessRoute
  '/api/search': typeof ApiSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/browse'
    | '/api/containers'
    | '/api/request-access'
    | '/api/search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/browse'
    | '/api/containers'
    | '/api/request-access'
    | '/api/search'
  id:
    | '__root__'
    | '/'
    | '/api/browse'
    | '/api/containers'
    | '/api/request-access'
    | '/api/search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiBrowseRoute: typeof ApiBrowseRoute
  ApiContainersRoute: typeof ApiContainersRoute
  ApiRequestAccessRoute: typeof ApiRequestAccessRoute
  ApiSearchRoute: typeof ApiSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/request-access': {
      id: '/api/request-access'
      path: '/api/request-access'
      fullPath: '/api/request-access'
      preLoaderRoute: typeof ApiRequestAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/containers': {
      id: '/api/containers'
      path: '/api/containers'
      fullPath: '/api/containers'
      preLoaderRoute: typeof ApiContainersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/browse': {
      id: '/api/browse'
      path: '/api/browse'
      fullPath: '/api/browse'
      preLoaderRoute: typeof ApiBrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiBrowseRoute: ApiBrowseRoute,
  ApiContainersRoute: ApiContainersRoute,
  ApiRequestAccessRoute: ApiRequestAccessRoute,
  ApiSearchRoute: ApiSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
